steps:
  - name: python:3.9
    entrypoint: "bash"
    args:
      - "test.sh"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "europe-west6-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "europe-west6-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "fastapi"
      - "--image=europe-west6-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi"
      - "--region=europe-west6"
      - "--allow-unauthenticated"
images:
  - "europe-west6-docker.pkg.dev/$PROJECT_ID/fastapi/fastapi"