steps:
  - name: python:3.9
    entrypoint: "bash"
    args:
      - "test.sh"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "eu.gcr.io/$PROJECT_ID/fastapi/fastapi"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "eu.gcr.io/$PROJECT_ID/fastapi/fastapi"